package com.maxkach.elasticlist.ui.screens.menu

import org.jetbrains.compose.resources.DrawableResource
import `scroll effect lazy`.sample_common.generated.resources.*

data class Dish(
    val id: Int,
    val section: String,
    val name: String,
    val resId: DrawableResource,
    val description: String,
    val price: String,
    val isSpicy: Boolean,
    val isVeg: Boolean,
)

val dishes = listOf(
    Dish(
        id = 1,
        section = "Starters",
        name = "Crispy Calamari",
        resId = Res.drawable.dish_01,
        description = "Lightly battered squid rings with lemon aioli and smoked paprika.",
        price = "$12",
        isSpicy = false,
        isVeg = false,
    ),
    Dish(
        id = 2,
        section = "Starters",
        name = "Burrata Plate",
        resId = Res.drawable.dish_02,
        description = "Creamy burrata, heirloom tomatoes, basil oil, grilled sourdough.",
        price = "$14",
        isSpicy = false,
        isVeg = true,
    ),
    Dish(
        id = 3,
        section = "Starters",
        name = "Crab Cakes",
        resId = Res.drawable.dish_03,
        description = "Pan-seared Maryland crab cakes with remoulade sauce.",
        price = "$16",
        isSpicy = false,
        isVeg = false,
    ),
    Dish(
        id = 4,
        section = "Starters",
        name = "Roasted Beet Salad",
        resId = Res.drawable.dish_04,
        description = "Golden beets, goat cheese, candied walnuts, citrus vinaigrette.",
        price = "$11",
        isSpicy = false,
        isVeg = true,
    ),
    Dish(
        id = 5,
        section = "Mains",
        name = "Tom Yum Goong",
        resId = Res.drawable.dish_05,
        description = "Spicy Thai shrimp soup with lemongrass and mushroom.",
        price = "$18",
        isSpicy = true,
        isVeg = false,
    ),
    Dish(
        id = 6,
        section = "Mains",
        name = "Truffle Risotto",
        resId = Res.drawable.dish_06,
        description = "Arborio rice slow-cooked with black truffle and aged parmesan.",
        price = "$24",
        isSpicy = false,
        isVeg = true,
    ),
    Dish(
        id = 7,
        section = "Mains",
        name = "Wagyu Burger",
        resId = Res.drawable.dish_07,
        description = "A5 wagyu patty, aged cheddar, bacon jam, brioche bun.",
        price = "$28",
        isSpicy = false,
        isVeg = false,
    ),
    Dish(
        id = 8,
        section = "Mains",
        name = "Spicy Korean Bibimbap",
        resId = Res.drawable.dish_08,
        description = "Rice bowl with seasonal vegetables, gochujang, fried egg.",
        price = "$17",
        isSpicy = true,
        isVeg = true,
    ),
    Dish(
        id = 9,
        section = "Mains",
        name = "Pan-seared Salmon",
        resId = Res.drawable.dish_09,
        description = "Atlantic salmon, lemon butter, asparagus, fingerling potatoes.",
        price = "$26",
        isSpicy = false,
        isVeg = false,
    ),
    Dish(
        id = 10,
        section = "Desserts",
        name = "Tiramisu",
        resId = Res.drawable.dish_10,
        description = "Classic mascarpone, espresso-soaked ladyfingers, cocoa dust.",
        price = "$9",
        isSpicy = false,
        isVeg = true,
    ),
    Dish(
        id = 11,
        section = "Desserts",
        name = "Matcha Cheesecake",
        resId = Res.drawable.dish_11,
        description = "Baked matcha cheesecake with white chocolate crumb.",
        price = "$10",
        isSpicy = false,
        isVeg = true,
    ),
    Dish(
        id = 12,
        section = "Desserts",
        name = "Chocolate Lava Cake",
        resId = Res.drawable.dish_12,
        description = "Warm chocolate cake with molten center and vanilla ice cream.",
        price = "$11",
        isSpicy = false,
        isVeg = true,
    ),
)
