package com.maxkach.elasticlist.ui.screens.ecommerce

import org.jetbrains.compose.resources.DrawableResource
import `scroll effect lazy`.sample_common.generated.resources.*

data class Product(
    val id: Int,
    val name: String,
    val resId: DrawableResource,
    val brand: String,
    val price: String,
    val oldPrice: String?,
    val rating: Double,
    val reviews: Int,
)

val products = listOf(
    Product(
        id = 1,
        name = "Air Cloud Runner",
        resId = Res.drawable.product_01,
        brand = "Nike",
        price = "$129",
        oldPrice = "$159",
        rating = 4.6,
        reviews = 128,
    ),
    Product(
        id = 2,
        name = "Studio Pro Headphones",
        resId = Res.drawable.product_02,
        brand = "Sony",
        price = "$349",
        oldPrice = null,
        rating = 4.8,
        reviews = 412,
    ),
    Product(
        id = 3,
        name = "Leather Biker Jacket",
        resId = Res.drawable.product_03,
        brand = "AllSaints",
        price = "$520",
        oldPrice = "$620",
        rating = 4.4,
        reviews = 56,
    ),
    Product(
        id = 4,
        name = "Classic Aviators",
        resId = Res.drawable.product_04,
        brand = "RayBan",
        price = "$179",
        oldPrice = null,
        rating = 4.7,
        reviews = 238,
    ),
    Product(
        id = 5,
        name = "Mechanical Keyboard",
        resId = Res.drawable.product_05,
        brand = "Keychron",
        price = "$159",
        oldPrice = "$199",
        rating = 4.5,
        reviews = 84,
    ),
    Product(
        id = 6,
        name = "Trail Backpack 30L",
        resId = Res.drawable.product_06,
        brand = "Osprey",
        price = "$149",
        oldPrice = null,
        rating = 4.9,
        reviews = 301,
    ),
    Product(
        id = 7,
        name = "Espresso Machine",
        resId = Res.drawable.product_07,
        brand = "Breville",
        price = "$699",
        oldPrice = "$799",
        rating = 4.6,
        reviews = 47,
    ),
    Product(
        id = 8,
        name = "Ultraboost Light",
        resId = Res.drawable.product_08,
        brand = "Adidas",
        price = "$189",
        oldPrice = null,
        rating = 4.3,
        reviews = 92,
    ),
    Product(
        id = 9,
        name = "Wool Crew Sweater",
        resId = Res.drawable.product_09,
        brand = "Uniqlo",
        price = "$69",
        oldPrice = "$89",
        rating = 4.5,
        reviews = 210,
    ),
    Product(
        id = 10,
        name = "Titanium Watch",
        resId = Res.drawable.product_10,
        brand = "Seiko",
        price = "$459",
        oldPrice = null,
        rating = 4.8,
        reviews = 134,
    ),
)
